HOST = '<your-ftp-server>'
USERNAME = '<your-username>'
PASSWORD = '<your-password>'
BASEDIR = '<your-starting-directory>'
KEYWORD = '<keyword-for-delete-line>'
BADWORD = '<badword-for-flag-file>'
FILENAME = '<file-name-for-delete-file>'
